name: fitlife
description: Gamified fitness tracker (MVP)

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0

  # Data/model
  
  json_annotation: ^4.9.0

  # Local storage (Isar seçtin)


dev_dependencies:
  build_runner: ^2.7.1
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1

  
  

# ---- Flutter varlıkları (assets) ----
flutter:
  uses-material-design: true
  assets:
     - assets/icons/
     - assets/images/
    # icon’u da asset olarak tutuyorsan:
    # - assets/icons/fitlife_logo_transperent.png

# ---- Splash ekran konfigürasyonu ----
flutter_native_splash:
  color: "#000000"
  image: assets/images/fitlife_splash.png
  android_12:
    image: assets/images/fitlife_splash.png
    color: "#000000"


# ---- Uygulama ikonu konfigürasyonu (transparent PNG önerilir) ----
flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/icons/fitlife_icon.png"     # sadece F+şimşek olan

  adaptive_icon_background: "#F2C24F"              # sarı arka plan
  adaptive_icon_foreground: "assets/icons/fitlife_icon.png"
