name: fitlife
description: Gamified fitness tracker (MVP)

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^17.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

flutter_launcher_icons:
  adaptive_icon_background: "#F2C24F"
  adaptive_icon_foreground: "assets/icons/fitlife_icon.png"
  android: true
  ios: true
  image_path: "assets/icons/fitlife_icon.png"

flutter_native_splash:
  android_12:
    color: "#000000"
    image: assets/images/fitlife_splash.png
  color: "#000000"
  image: assets/images/fitlife_splash.png
