name: fitlife
description: Gamified fitness tracker (MVP)

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  dio: ^5.0.0
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^18.0.1
  flutter_riverpod: ^2.6.1
  flutter_timezone: ^3.0.1
  go_router: ^17.0.0
  google_generative_ai: ^0.4.7
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.6.0
  intl: ^0.19.0 
  json_annotation: ^4.8.1
  timezone: ^0.9.4
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/json/default_exercises.json
    - .env.example

flutter_launcher_icons:
  adaptive_icon_background: "#F2C24F"
  adaptive_icon_foreground: "assets/icons/fitlife_icon.png"
  android: true
  ios: true
  image_path: "assets/icons/fitlife_icon.png"

flutter_native_splash:
  android_12:
    color: "#000000"
    image: assets/images/fitlife_splash.png
  color: "#000000"
  image: assets/images/fitlife_splash.png
