name: fitlife
description: Gamified fitness tracker (MVP)
environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.7.1 
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter 
  freezed: ^3.2.3
  json_serializable: ^6.11.1
